config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # resources :categories
  devise_for :admins, path: 'admin', skip: :registrations
  devise_for :users
  # devise_for :adminposts
  # STEP 1: A ROUTE triggers a controller action
  # verb "/urls" => "namespace/controllers#action"

  # namespace :admin do
    # resources :adminposts
    resources :categories
    resources :courses
  # end

  # get 'admin' => 'admin/posts#index'


  root 'courses#index'
  # root 'home#index'
  
  # get "/" => "course#index"
  get "/about" => "courses#about"
  get "/classes" => "courses#classes"
  # get "/classes/:id" => "courses#show", as: "course"
  
  # get "classes/new" => "courses#new", as: "new_course"
  post "course" => "courses#create"
  # get "/list" => "courses#list"

  get "/contact" => "courses#contact"

  get "/adminposts" => "adminposts#index"
  get "/adminposts/:id" => "adminposts#show"
  get "/adminposts/new" => "adminposts#new"

  post "/adminpost/new" => "adminposts#create"

  # get '/contact', to: 'messages#new', as: 'new_message'
  # post '/contact', to: 'messages#create', as: 'create_message'


  # get "/courses" => "course#courses"
  # post "/contact" => "course#contact"
  # patch 'course/:id' => 'course#update'
  # delete 'course/:id' => 'course#destroy'

end

app/models/admin_post.rb
class AdminPost < ApplicationRecord
   validates :title, presence: true
   validates :content, presence: true
   # validates :category, presence: true
end

app/models/adminpost.rb
class Adminpost < ApplicationRecord
   validates :title, presence: true
   validates :content, presence: true
   # validates :category, presence: true
end

app/controllers/admin/AdminPosts_controller.rb
class Admin::admin_postsController < ApplicationController
  before_action :set_admin_post, only: [:show, :edit, :update, :destroy]

  def admin_post_params
    params.require(:admin_post).permit(:title, :content, :category_id)
  end
  
  # GET /admin/admin_posts
  # GET /admin/admin_posts.json
  def index
    @admin_admin_posts = AdminPost.all
  end

  # GET /admin/admin_posts/1
  # GET /admin/admin_posts/1.json
  def show
  end

  # GET /admin/posts/new
  def new
    @admin_post = AdminPost.new
  end

  # GET /admin/posts/1/edit
  def edit
  end

  # POST /admin/posts
  # POST /admin/posts.json
  def create
    @admin_post = AdminPost.new(admin_post_params)

    respond_to do |format|
      if @admin_post.save
        format.html { redirect_to [:admin, @admin_post], notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @admin_post }
      else
        format.html { render :new }
        format.json { render json: @admin_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/posts/1
  # PATCH/PUT /admin/posts/1.json
  def update
    respond_to do |format|
      if @admin_post.update(admin_post_params)
        format.html { redirect_to [:admin, @admin_post], notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_post }
      else
        format.html { render :edit }
        format.json { render json: @admin_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/posts/1
  # DELETE /admin/posts/1.json
  def destroy
    @admin_post.destroy
    respond_to do |format|
      format.html { redirect_to [:admin, @admin_post], notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_post
      @admin_post = AdminPost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_post_params
      params.fetch(:admin_post, {})
    end
end

app/controllers/adminposts_Controller.rb
class AdminpostsController < ApplicationController
  before_action :set_adminpost, only: [:show, :edit, :update, :destroy]

  def adminpost_params
    params.require(:adminpost).permit(:title, :content)
  end
  
  # GET /admin/adminposts
  # GET /admin/adminposts.json
  def index
    @adminposts = Adminpost.all
    render 'adminposts/about.html.erb'
    # render json: @adminposts
  end

  # GET /admin/adminposts/1
  # GET /admin/adminposts/1.json
  def show
    @adminpost = Adminpost.find(params[:id])
    render json: @adminpost
  end

  def new
    @adminpost = Adminpost.new
    render 'adminposts/_form.html.erb'
    # render 'admin/adminposts/_form.html.erb'
  end

  # GET /admin/posts/1/edit
  def edit
  end

  # POST /admin/posts
  # POST /admin/posts.json
  def create
    @adminpost = Adminpost.new(adminpost_params[:title, :content])

    respond_to do |format|
      if @adminpost.save
        format.html { redirect_to [:admin, @adminpost], notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @adminpost }
      else
        format.html { render :new }
        format.json { render json: @adminpost.errors, status: :unprocessable_entity }
      end
    end
  end


# course create action (adapt to save adminposts as new course entries)
#   def create
#    @course = Course.new(name: params[:name],
#                   description: params[:description]
#                  )
#    @course.save
#    render json: {message: "Element successfully created"} 
#   end



  # PATCH/PUT /admin/posts/1
  # PATCH/PUT /admin/posts/1.json
  def update
    respond_to do |format|
      if @adminpost.update(adminpost_params)
        format.html { redirect_to [:admin, @adminpost], notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @adminpost }
      else
        format.html { render :edit }
        format.json { render json: @adminpost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/posts/1
  # DELETE /admin/posts/1.json
  def destroy
    @adminpost.destroy
    respond_to do |format|
      format.html { redirect_to [:admin, @adminpost], notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_adminpost
      @adminpost = Adminpost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    # def adminpost_params
    #   params.fetch(:admin_post, {})
    # end
end

app/views/adminposts/_form.html.erb
<%= form_with(model: @adminpost do |form| %>


  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= f.submit "Create" %>
  </div>
<% end %>

app/views/adminposts/edit.html.erb
<h1>Editing admin_post</h1>

<%= render 'form', admin_post: @admin_post %>

<%= link_to 'Show', admin_admin_post_path(params[:id]) %> |
<%= link_to 'Back', admin_admin_posts_path %>

app/views/adminposts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Admin Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @adminposts.each do |adminpost| %>
      <tr>
        <td><%= adminpost.title %></td>
        <td><%= adminpost.content %></td>
        <td><%= link_to 'Show', adminposts_path(@adminpost) %></td>
        <!-- removed edit path -->
        <td><%= link_to 'Destroy', adminposts_path(:id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<!-- removed create new path -->

<br>



<br>
<br>
  
<ul>
  <li><a href="/">Home</a></li>
  <li><a href="/../about.html">About</a></li>
  <li><a href="/../classes.html">Classes</a></li>
  <li><a href="/../contact.html">Contact</a></li>
</ul>
     

app/views/adminposts/new.html.erb
<h1>New Admin Post</h1>

<%= render 'form', admin_post: @admin_post %>

<%= link_to 'Back', @admin_posts_path %>

app/views/adminposts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @admin_post.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @admin_post.content %>
</p>

<%= link_to 'Edit', edit_admin_admin_post_path(@admin_post) %> |
<%= link_to 'Back', admin_admin_posts_path %>