config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # resources :categories
  devise_for :admins, path: 'admin', skip: :registrations
  devise_for :users
  # devise_for :adminposts
  # STEP 1: A ROUTE triggers a controller action
  # verb "/urls" => "namespace/controllers#action"

  # namespace :admin do
    # resources :adminposts
    resources :categories
    resources :courses
  # end

  # get 'admin' => 'admin/posts#index'


  root 'courses#index'
  # root 'home#index'
  
  # get "/" => "course#index"
  get "/about" => "courses#about"
  get "/classes" => "courses#classes"
  # get "/classes/:id" => "courses#show", as: "course"
  
  # get "classes/new" => "courses#new", as: "new_course"
  post "course" => "courses#create"
  # get "/list" => "courses#list"

  get "/contact" => "courses#contact"

  get "/adminposts" => "adminposts#index"
  get "/adminposts/:id" => "adminposts#show"
  get "/adminposts/new" => "adminposts#new"

  post "/adminpost/new" => "adminposts#create"

  # get '/contact', to: 'messages#new', as: 'new_message'
  # post '/contact', to: 'messages#create', as: 'create_message'


  # get "/courses" => "course#courses"
  # post "/contact" => "course#contact"
  # patch 'course/:id' => 'course#update'
  # delete 'course/:id' => 'course#destroy'

end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  before_action :set_admin_category, only: [:show, :edit, :update, :destroy]

  # GET /admin/categories
  # GET /admin/categories.json
  def index
    @admin_categories = Category.all
  end

  # GET /admin/categories/1
  # GET /admin/categories/1.json
  def show
  end

  # GET /admin/categories/new
  def new
    @admin_category = Category.new
  end

  # GET /admin/categories/1/edit
  def edit
  end

  # POST /admin/categories
  # POST /admin/categories.json
  def create
    @admin_category = Category.new(admin_category_params)

    respond_to do |format|
      if @admin_category.save
        format.html { redirect_to @admin_category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @admin_category }
      else
        format.html { render :new }
        format.json { render json: @admin_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/categories/1
  # PATCH/PUT /admin/categories/1.json
  def update
    respond_to do |format|
      if @admin_category.update(admin_category_params)
        format.html { redirect_to @admin_category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_category }
      else
        format.html { render :edit }
        format.json { render json: @admin_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/categories/1
  # DELETE /admin/categories/1.json
  def destroy
    @admin_category.destroy
    respond_to do |format|
      format.html { redirect_to admin_categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_category
      @admin_category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_category_params
      params.fetch(:admin_category, {})
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_admin_category, only: [:show, :edit, :update, :destroy]

  # GET /admin/categories
  # GET /admin/categories.json
  def index
    @admin_categories = Category.all
  end

  # GET /admin/categories/1
  # GET /admin/categories/1.json
  def show
  end

  # GET /admin/categories/new
  def new
    @admin_category = Category.new
  end

  # GET /admin/categories/1/edit
  def edit
  end

  # POST /admin/categories
  # POST /admin/categories.json
  def create
    @admin_category = Category.new(admin_category_params)

    respond_to do |format|
      if @admin_category.save
        format.html { redirect_to @admin_category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @admin_category }
      else
        format.html { render :new }
        format.json { render json: @admin_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/categories/1
  # PATCH/PUT /admin/categories/1.json
  def update
    respond_to do |format|
      if @admin_category.update(admin_category_params)
        format.html { redirect_to @admin_category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_category }
      else
        format.html { render :edit }
        format.json { render json: @admin_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/categories/1
  # DELETE /admin/categories/1.json
  def destroy
    @admin_category.destroy
    respond_to do |format|
      format.html { redirect_to admin_categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_category
      @admin_category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_category_params
      params.fetch(:admin_category, {})
    end
end

app/views/admin/categories/_form.html.erb
<%= form_with(model: admin_category, local: true) do |form| %>
  <% if admin_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(admin_category.errors.count, "error") %> prohibited this admin_category from being saved:</h2>

      <ul>
      <% admin_category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="name">
    <%= form.label :name %>
    <%= form.text_field :title %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/categories/edit.html.erb
<h1>Editing Admin Category</h1>

<%= render 'form', admin_category: @admin_category %>

<%= link_to 'Show', @admin_category %> |
<%= link_to 'Back', admin_categories_path %>

app/views/admin/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Admin Categories</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @admin_categories.each do |admin_category| %>
      <tr>
        <td><%= link_to 'Show', admin_category %></td>
        <td><%= link_to 'Edit', edit_admin_category_path(admin_category) %></td>
        <td><%= link_to 'Destroy', admin_category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Admin Category', new_admin_category_path %>

app/views/admin/categories/new.html.erb
<h1>New Admin Category</h1>

<%= render 'form', admin_category: @admin_category %>

<%= link_to 'Back', admin_categories_path %>

app/views/admin/categories/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_admin_category_path(@admin_category) %> |
<%= link_to 'Back', admin_categories_path %>